name: build
on:
  workflow_dispatch:
  push:
    branches: [ master, main ]
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/build.yml'

permissions:
  actions: none
  checks: none
  contents: none
  deployments: none
  issues: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        ndk:
          - "26.0.10792818"
          - "25.2.9519653"
        libraryType:
          - "shared"
          - "static"
        package:

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - uses: android-actions/setup-android@v3
      - run: sdkmanager "ndk;${{ matrix.ndk }}"
      - run: pip3 install --user ninja meson

      - run: ./gradlew ${{ matrix.package }}:publishToMavenLocal -PndkPath=${{ env.ANDROID_SDK_ROOT }}/ndk/${{ matrix.ndk }} -PlibraryType=${{ matrix.libraryType }}

      - uses: actions/upload-artifact@v3
        with:
          name: "${{ matrix.package }}-${{ matrix.ndk }}-logs"
          path: "${{ matrix.package }}/build/port/logs"
          if-no-files-found: error

      - run: tar -cvf maven-local.tar ~/.m2
      - uses: actions/upload-artifact@v3
        with:
          name: "${{ matrix.package }}-${{ matrix.ndk }}.maven-local.tar"
          path: maven-local.tar
          if-no-files-found: error

