name: fontforge
on:
  workflow_dispatch:
  push:
    paths:
      - 'buildSrc/**'
      - '.github/workflows/build.yml'
      - 'fontforge/**'
      - '.github/workflows/fontforge.yml'
jobs:
  build-fontforge-20230101:
    name: fontforge 20230101
    uses: ./.github/workflows/build.yml
    with:
      package: fontforge
      version: '20230101'
      apt_packages: gettext
