name: fribidi
on:
  workflow_dispatch:
  push:
    paths:
      - 'buildSrc/**'
      - 'fribidi/**'
      - '.github/workflows/build.yml'
      - '.github/workflows/fribidi.yml'

jobs:
  build:
    name: fribidi
    uses: ./.github/workflows/build.yml
    with:
      package: fribidi
