name: libjpeg-turbo
on:
  workflow_dispatch:
  push:
    paths:
      - 'buildSrc/**'
      - 'libjpeg-turbo/**'
      - '.github/workflows/build.yml'
      - '.github/workflows/libjpeg-turbo.yml'

jobs:
  build:
    name: libjpeg-turbo
    uses: ./.github/workflows/build.yml
    with:
      package: libjpeg-turbo
