name: libtiff
on:
  workflow_dispatch:
  push:
    paths:
      - 'buildSrc/**'
      - 'libtiff/**'
      - '.github/workflows/build.yml'
      - '.github/workflows/libtiff.yml'

jobs:
  build:
    name: libtiff
    uses: ./.github/workflows/build.yml
    with:
      package: libtiff
