name: pango
on:
  workflow_dispatch:
  push:
    paths:
      - 'buildSrc/**'
      - 'pango/**'
      - '.github/workflows/build.yml'
      - '.github/workflows/pango.yml'

jobs:
  build-pango-current:
    name: pango 1.51.0
    uses: ./.github/workflows/build.yml
    with:
      package: pango
      version: 1.51.0

  build-pango-legacy:
    name: pango 1.49.4
    uses: ./.github/workflows/build.yml
    with:
      package: pango
      version: 1.49.4
