name: pdf2htmlEX
on:
  workflow_dispatch:
  push:
    paths:
      - 'buildSrc/**'
      - '.github/workflows/build.yml'
      - 'pdf2htmlEX/**'
      - '.github/workflows/pdf2htmlEX.yml'

jobs:
  build-pdf2htmlEX-0_18_8_rc2:
    name: pdf2htmlEX 0.18.8.rc2
    uses: ./.github/workflows/build.yml
    with:
      package: pdf2htmlEX
      version: '0.18.8.rc2'
