name: poppler
on:
  workflow_dispatch:
  push:
    paths:
      - 'buildSrc/**'
      - '.github/workflows/build.yml'
      - 'poppler/**'
      - '.github/workflows/poppler.yml'

jobs:
  build:
    name: poppler
    uses: ./.github/workflows/build.yml
    with:
      package: poppler
