name: poppler
on:
  workflow_dispatch:
  push:
    paths:
      - 'buildSrc/**'
      - '.github/workflows/build.yml'
      - 'poppler/**'
      - '.github/workflows/poppler.yml'

jobs:
  build-poppler-23_12_0:
    name: poppler 23.12.0
    uses: ./.github/workflows/build.yml
    with:
      package: poppler
      version: '23.12.0'
