name: wvWare
on:
  workflow_dispatch:
  push:
    paths:
      - 'buildSrc/**'
      - 'wvWare/**'
      - '.github/workflows/build.yml'
      - '.github/workflows/wvWare.yml'

jobs:
  build:
    name: wvWare
    uses: ./.github/workflows/build.yml
    with:
      package: wvware
